# Generated by Django 5.1.1 on 2024-10-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_adminuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='full_name',
        ),
    ]
