# Generated by Django 5.1.1 on 2024-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_adminuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/passport_photos/'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos/'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='town_village_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
